### ISSUE TITLE
option to download zip without music

### ISSUE THREAD

**Issue by funjobie** [beatsaver/beatsaver#10]
Hi,

i think it would be great if we could also download the track files directly / or the zip without the ogg/cover files. could be a seperate button for it.
that way i could then add the music locally myself, which has the benefit of not getting a headache over the licenses (for those that care, anyway).
(there might be a mismatch with the start offset but that probably can be corrected afterwards)

**Comment by beatsaver** [comment]
At this time, I do not do any form of modification on what is uploaded, only check what is inside the zip. so what ever got uploaded stays in its true form

**Comment by funjobie** [comment]
i see. what i was thinking of was keeping the uploaded zip as is, but also to create a new zip while parsing the old, which just has the json files, and store that too (similar to how the image is stored also under file_put_contents("img/$uid.".$imageFileType, $imgdata); )
