### ISSUE TITLE
Add a way to allow map creators to update some of info.json

### ISSUE THREAD

**Issue by SilentNightx** [beatsaver/beatsaver#12]
According to others this would not affect leaderboards and would allow people like me who forgot something, in my case setting proper preview times, to fix it without losing their download stats and ratings.

**Comment by Sluder** [comment]
This could definitely be something we could add in the new site, we'll double check to make sure leader boards wont be affected

**Comment by beatsaver** [comment]
At this time, I have a hands off policy on uploaded files, I only verify the contents, please be more careful in the future

**Comment by Sluder** [comment]
Why? I don't see any security issues with modifying the files
