### ISSUE TITLE
User Profiles page with list of songs uploaded

### ISSUE THREAD

**Issue by JDiPierro** [beatsaver/beatsaver#13]
When I find a mapping I really enjoy I'd like to be able to see all songs uploaded by that user. I tried searching by their name and that didn't seem to work, and couldn't find a link to any sort of profile.

Also, The alpha UI seems to be completely lacking the name of the author on the mapping's page.

**Comment by beatsaver** [comment]
This is happening in the rewrite, a code freeze is pretty much in place.
