### ISSUE TITLE
Make an upvote/downvote system instead of stars.

### ISSUE THREAD

**Issue by juliusfrost** [beatsaver/beatsaver#5]
There is no current usage for the star system as a ranking of songs. I believe there needs to be an upvoting system so that players can gauge good and bad charts, so that people do not waste time downloading a song that was poorly made. By implementing this feature we can quickly make a standard for creating charts as it would make the songs more organized. Also, this should be implemented into the game as a mod too so that people can easily rate charts in game.

**Comment by beatsaver** [comment]
I've been having ideas to move the whole thing to some type of pre-built community platform and edit it to my needs

**Comment by juliusfrost** [comment]
Great! Would love to see that

**Comment by Invertex** [comment]
Hopefully some sort of OAUTH system in-place as well so that people can login their BeatSaver account in-game and do voting from within the menu. This would greatly improve vote participation.

**Comment by beatsaver** [comment]
I would just use their ID that the scoreboards would use.

**Comment by Invertex** [comment]
Well, the only issue with that is people can easily just put in whoever's ID they want. With Steam login authorization it's a lot more secure. I worry about the kind of abuse that might allow but guess it's not a big deal.

**Comment by beatsaver** [comment]
that IS their steam login :P

**Comment by Invertex** [comment]
Are you talking about the ID that BeatSaber itself has access to? I assumed you were talking about them just having a manually input one. If so then yeah that's good, didn't know BeatSaber offered that info to the API.
