### ISSUE TITLE
Make it possible to edit previously submitted songs

### ISSUE THREAD

**Issue by juliusfrost** [beatsaver/beatsaver#6]
There are few songs submitted that are perfect. Notes, lighting, name, image, etc... all have to be considered each time one uploads a song. And it's almost impossible to get it right the first time.

**Comment by beatsaver** [comment]
This cannot happen at this time, Due to the way scoreboards work they take the entire diff file for that diff and hash it, that's what is used for scoreboards -- So Updating a file is making the file a lie to what was downloaded before

**Comment by lilfade** [comment]
Could always keep a hash of the new song alongside the old and have the scoreboard factor this small change in. Not sure if this would be a small change or not currently as i haven't looked at anything ^_^.

**Comment by beatsaver** [comment]
Don't forget about cheating then, overall, you should be testing and releasing your songs when you are well done
